lines = [
    "1C_334/2020",
    "démolir la terrasse agrandie dans un délai de 30 jours à compter de la réception de la présente décision.",
    "50 mètres carrés",
    "La qualité des cheminements et la continuité des traversées",
    "Demande d'autorisation de construire pour l'agrandissement d'une terrasse existante",
    "7, \"blocks\": [{ \"block_type\": \"text\", \"block_content\": \"Dans le cas d'espèce, pour atteindre les objectifs fixés par l'ISOS et le PDCant, elle a décidé de lui su...",
    "07h00",
    "45 dB(A)",
    "Refus de la demande et ordre de démolir",
    "1/8",
    "Commission des finances de la Ville de Fribourg",
    "ATF 115 la 353",
    "Signature 2 Une Décision Arrêté à Morges",
    "11 juin 2020",
    "TC 602 2021 72 consid. 3.3",
    "Tribunal administratif de première instance",
    "Service de l'Urbanisme et de l'Aménagement du Territoire",
    "Le Dilemme d'Urs Meier : Un Conflit Successoral et une Décision Communale Inattendue",
    "134 al. 1 CPJA",
    "« La demande d'autorisation de construire  »",
    "La qualité des cheminements et la continuité des traversées piétonnes doivent être assurées (al. 4).",
    "2023-1234",
    "1C_87/2019",
    "T115 « sites construits protégés et chemins historiques »",
    "e. De ce fait, toute intervention nécessite préalablement l'élaboration d'un plan paysager (al. 1).",
    "Le Service de la population de la commune de Lausanne",
    "3. Précise que, faute de démolition dans le délai imparti, la commune se réserve le droit de procéder à la démolition d'office",
    "2 du Code du 23 mai 1991 de procédure et de juridiction administrative (CPJA ; RSF 150.1)",
    "La substance bâtie (chalets et villa bourgeoises) doit être préservée.",
    "60 dB(A)",
    "12'587",
    "RSF 150.1",
    "16 de la Loi sur les amendes d'ordre du canton de Zurich (LAO), Nous ordonnons : 1.",
    "Objet :",
    "CHF 500.- par jour de retard",
    "Concerne: Demande d'autorisation de construire pour l'agrandissement d'une terrasse existante",
    "30 jours",
    "T115.",
    "commune",
    "Considérant:",
    "2 la Commune de Fribourg",
    "ATF 132 III 706",
    "Le Courrier Fribourgeois",
    "1 Veuillez agréer, Madame, l'expression de nos salutations distinguées.",
    "22h01",
    """résidérant": L'article 6 alinéa 2 de la Loi vaudoise sur l'exercice du commerce (LEC) qui stipule que "L'exercice du commerce doit se faire dans le respect des intérêts l""" ,
    "131 II 121",
    "aces publics.",
    "15 juin 2024",
    "Objet: Refus de la demande et ordre de démolir",
    "30 septembre 2024",
    "Nous",
    "RCU",
    "population",
    "E ISOS 25",
    "LEX",
    "LFinCom",
    "Considérant",
    "RSF 710.1",
    "périmètre",
    "Service de l'urbanisme et des constructions",
    "Conseil communal",
    "Enduits d'oiseaux",
    "Interdiction d'activités de yoga dans le parc public de",
    "T115",
    "RS 700",
    "LC 87",
    "RCB",
    "LAT",
    "Voies de recours",
    "Page 1/1",
    "Le Gourmet Égaré",
    "ZRP1",
    "harmonisation",
    "Fédérant",
    "décision communale",
    "LCR",
    "Commune de Fribourg",
    "mesures",
    "LATec",
    "Signature 2",
    "Le Chef",
    "1C_334/2020",
    "RCU/EVP",
    "Zch-Th",
    "CPJA",
    "LATC",
    "ores, notamment en limitant le volume sonore de vos activités nocturnes. 1 2. Prendr",
    "PAL",
    "publics",
    "LGCZ",
    "PPS",
    "bassin",
    "véranda",
    "T. blocks : [ { \"block_type\": \"text\", \"block_content\": \"Dans le cas d'espèce, pour attein",
    "RCPB",
    "Fatidique",
    "L'Expropriation",
    "Les émissions sonores",
    "CMNS",
    "parc",
    "Un jour, il reçoit une lett",
    "Locations",
    "frères et sœurs",
    "LP01",
    "dimanches et jours fériés",
    "LHID",
    "bâtants",
    "Service des espaces verts et du domaine public",
    "Madame,",
    "Service",
    "intérêts",
    "Page 2/2",
    "200 francs suisses",
    "Ville de Zurich",
    "mangeoires",
    "valeurs",
    "PDCant",
    "Objet: Mise en conformité de la haie mitoyenne",
    "Loi sur les constructions du canton du Valais (LC)",
    "s de la route et constitue un danger pour la sécurité routière, en violation de l'article 29 de la loi sur la",
    "s, votre participation à la vie sociale et culturelle locale semble limitée.",
    "sanctions",
    "LATeC; RSF 710.1",
    "Décision",
    "Commune de Genève",
    "Articles du PLU pertinents",
    "Municipal chargé du commerce et du tourisme",
    "Règlement communal sur l'utilisation des espaces verts et du domaine public (RCUEVDP)",
    "paysagère",
    "autonomie",
    "migrations",
    "Règlement communal",
    "article 68",
    "RIC",
    "ATF",
    "Motta",
    "LAT; RS 700",
    "Monsieur",
    "Rhodanie",
    "article 3",
    "ISO5",
    "RDAF",
    "Ste",
    "RCP",
    "PAZ",
    "opposition",
    "ReLATeC; RSF 710.1",
    "12'587",
    "RSF 150.1",
    "Ferme familiale",
    "Service de",
    "ture végétale nécessite l'élaboration d'un plan paysager (al. 1). Partant, les objectifs fixés par l'ISOS s",
    "Motta",
    "RCC",
    "ispositions légales en vigueur et porte atteinte aux droits de votre voisin",
    "AIHC",
    "30 jours",
    "Service de l'Urbanisme et de l'Aménagement du Te",
    "Signature",
    "communale",
    "Règlement communal sur les plantations",
    "bitants.",
    "buts",
    "dispositions légales en vigueur et porte atteinte aux droits de votre voisin. En outre, votre construction n'a pas fait l'objet d'un permis de construire.",
    "ISOS",
    "article 55",
    "nichoirs",
    "visés",
    "mpter",
    "omme",
    "LPol",
    "intersection",
    "StG",
    "colere",
    "Le recours doit être formé par écrit et motivé. Il doit indiquer les conclusions, les moyens de preuve et l'objet du litige",
    "horloger",
    "Département des finances",
    "Décision de mainlevée de l'opposition",
    "Service des poursuites et faillites",
    "Administration fiscale",
    "Le responsable du service des poursuites et faillites",
    "paisible retraité de Locarno",
    "Fournisseurs Suisses de Qualité",
    "1 Votre responsabilité est donc engagée sur le fondement de l'article 41 du Code des obligations (CO), qui dispose que \"celui qui cause un dommage à autrui par son fait illicite est tenu de le ré - N_ce48",
    "Mon-Dossier.ch",
    "Opposa",
    "Renault Clio",
    "Mise en Demeure Fournisseurs Suisses de Qualité SA",
    "Administration fiscale cantonale",
    "FSQ",
    "mon-dossier.ch",
    "montant de CHF 3'100.-",
    "CHF 8'500.-, augmentée des intérêts moratoires calculés au taux légal de 5% depuis le",
    "3. Les frais de la présente procédure",
    "Fournisseurs Suisses de Qualité",
    "Concerne: Parcelle n° 5678",
    "CHF 3'600.-",
    "Bénéficiaire du legs",
    "ne",
    "colère",
    "Recours",
    "Attendu que: 1 • Que la parcelle n° 5678 est grevée d'un droit de préemption communal établi par la décision du Conseil communal du [Date], conformément à",
    "Klinikdirektor",
    "Solidaritätszuschlag",
    "Ausländerbehörde München",
    "Einkommensteuer",
    "Gesamtsteuerbetrag",
    "Das Amtsgericht Hamburg",
    "Finanzamt Berlin-Neukölln",
    "Sollten Sie nicht reagieren, wird der Zahlungsbefehl rechtskräftig und der Gläubiger kann weit",
    "Tribunal de district de Sion",
    "Sozialversicherungsanstalt des Kantons Zürich",
    "Tribunal des prud'hommes de Lausanne",
    "Tribunal de district de Sion",
    "La Ville de Bâle",
    "Cependa",
    "Document Fictif : Décision de la commune de Genève COMMUNE DE GENEVE Département des finances Service des poursuites et faillites Décision de mainlevée de l'opposition",
    "positions légales en vigueur et porte atteinte aux droits de votre voisin. 1 En outre, votre construction n'a pas fait l'objet d'une autorisation de construire préalable, comme l'exige l'article 55 de la Loi sur l'aménagement du territoire et les constructions (LATC). Page 3 Par conséquent, nous vous enjoignons de procéder"
    "ibunal",
    "clause de non-responsabilité liée à la vitesse excessive",
    "Le Tribunal",
    "En vertu des articles 308 et suivants du Code de procédure civile suisse.",
    "code de procédure civile",
    "approbation",
    "commission",
    "Partie Adverse",
    "Exécution et Recours",
    "Alignement",
    "15 mètres",
    "Décision Juridique Tribunal de Première Instance du Canton de Genève",
    "Liquidateur",
    "plans",
    "Densité",
    "ojet",
    "psychologie",
    "Vous",
    "Révision des Dispositions",
    "Modification des terms financiers en raison de changement importants dans votre situation financière",
    "Découverte de vices cachés dans l'appartement, tels que des problèmes d'humidité non divulgués au moment de la vente",
    "Dépenses : Les frais de liquidation, incluant les honoraires du liquidateur et les frais administratifs, seront couverts par les actifs de la société. Si les actifs ne suffisent pas à couvrir ces frais, la différence sera répartie proportionnellement entre les créanciers.",
    "Objet : Décision concernant la demande de révision d'un testament",
    "n'a pas respecté les termes du contrat en fournissant des services de qualité insuffisante",
    "Délai d'appel : La décision peut être contestée en appel devant la Cour d'Appel du Canton de Vaud dans un délai de 30 jours à compter de",
    "Rous",
    "on.",
    "Conclusion",
    "Vérification des obligations contractuelles",
    "Analyse juridique",
    "Tribunal de Première instance de Neuchatêl",
    "Examen du contrat de services : Le contrat signé le 15 juillet 2023 précise les obligations de chaque partie",
    "Tribunal de Première instance de Genêve",
    "palais de justice",
    "examen du contrat de services",
    "conteste les accusations et soutient que",
    "présentation des personnages",
    "le tribunal doit déterminer si",
    "Résiliation parcielle du contrat",
    "Dépens",
    "Rejet de la plainte",
    "Examen du contrat de services",
    "Réparations",
    "condamnation des dépens",
    "rejet partiel de la plainte",
    "Introduction",
    "Contexte du litige",
    "Herzkatheteruntersuchungen und -interventionen",
    "Sehr geehrte",
    "Responsabilité et recours : Selon la législation suisse sur",
    "secteur",
    "Retirer ou déplacer les nichoirs à une distance suffisante de votre propriété et des habitations voisines.",
    "bosquets",
    "Tribunal de Commerce",
    "Assurances",
    "Ordonnance",
    "inventaires",
    "Procédure",
    "Monsieur, Mesdames du Tribunal de police de la Ville de Zurich ",
    "Ainsi",
    "Le Greffier",
    "Name der Zeitung",
    "a intenté une action en justice contre",
    "Etoile",
    "Klinik für Kardiologie",
    "Mettre en place des dispositifs dissuasifs (tels que des répulsifs sonores ou visuels) pour éloigner les oiseaux.",
    "articolo 9 dell'Ordinanza comunale per la protezione contro il rumore della Città di Lugano",

    "Herzkatheteruntersuchungen und -interventionen",
    "Sehr geehrte",
    "Responsabilité et recours : Selon la législation suisse sur",
    "secteur",
    "Retirer ou déplacer les nichoirs à une distance suffisante de votre propriété et des habitations voisines.",
    "bosquets",
    "Tribunal de Commerce",
    "Assurances",
    "Ordonnance",
    "inventaires",
    "Procédure",
    "Monsieur, Mesdames du Tribunal de police de la Ville de Zurich ",
    "Ainsi",
    "Le Greffier",
    "Name der Zeitung",
    "a intenté une action en justice contre",
    "Etoile",
    "Klinik für Kardiologie",
    "Mettre en place des dispositifs dissuasifs (tels que des répulsifs sonores ou visuels) pour éloigner les oiseaux.",
    "articolo 9 dell'Ordinanza comunale per la protezione contro il rumore della Città di Lugano - N_6f36",
    "inventaires fédéraux",
    "Le fournisseur d'électricité",
    "Preuves des défauts et retards : Les preuves fournies par Monsieur Bernard comprennent des photos des imperfections",
    "Umgangsrecht für Ihr gemeinsames Kind [Name des Kindes] mit dem Vater [Name des Vaters] hat das Familiengericht Köln am [Datum] fol",
    "frais de gestion de compte",
    "agents",
    "see",
    "Responsabilité du vendeur : En vertu de la législation suisse sur la vente, un vendeur peut être tenu responsable de défauts cachés",
    "conditions",
    "témoins",
    "Code des obligations suisse",
    "solde",
    "boisements",
    "A défaut, nous serons contraints de prendre des mesures plus coercitives, conformément à l'article 23 du RCUEVDP, qui prévoit",
    "arbres",
    "d'Appel du Canton de Fribourg",
    "Per",
    "lois",
    "systèmes d'irrigation",
    "Défense de Madame Meier",
    "Résiliation du contrat de vente : Le Tribunal décide de résilier le contrat de vente en raison de la présence",
    "terrasses",
    "Cour d'Appel",
    "Mon",
    "unal",
    "Réclamations de Monsieur Dubois",
    "Secrétaire de séance",
    "Pour toute correspondance, veuillez adresser vos lettres à l'adresse suivante",
    "Tribunal de Première instance du District de la Sarine",
    "Tribunal de première instace de l'ouest Lausannois",
    "Le Président du Tribunal Antoine Bouvier",
    "Tribunal de Première instance du District de Sierre",
    "pour les travaux non conformes",
    "Tribunal de Première Instance du District de Martigny",
    "Le litige concerne un contrat de prestation de services signé le",
    
]

from pymilvus.model.hybrid import BGEM3EmbeddingFunction
import torch
import numpy as np
import time

start_time = time.time()


bge_m3_ef = BGEM3EmbeddingFunction(
    model_name='BAAI/bge-m3', 
    device='cpu',
    return_sparse=False
)

name_embeddings_matrix = np.array(bge_m3_ef.encode_documents(lines)["dense"]).T  # Transpose to make each embedding a column

np.save('should_not_be_anon.npy', name_embeddings_matrix)
print(f"Matrix shape: {name_embeddings_matrix.shape}")
print("Matrix saved as should_not_be_anon.npy")

end_time = time.time()
execution_time = end_time - start_time
print(f"Execution time: {execution_time:.2f} seconds")